// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    FileSystemAccessApi: typeof import('./components/web-api/FileSystemAccessApi.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    ShareApi: typeof import('./components/web-api/ShareApi.vue')['default']
  }
}

export { }
